# Please consult conda-forge/core before doing this
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "12.0"                 # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "12.0"                 # [osx and x86_64]